#!/usr/bin/env python3
"""Local server: serves files + proxies AI requests to Pollinations.ai"""

import http.server
import json
import urllib.request
import urllib.parse
import ssl
import os
import time

PORT = 8000
API_URL = "https://text.pollinations.ai/"

# Fix macOS SSL
ssl_ctx = ssl.create_default_context()
ssl_ctx.check_hostname = False
ssl_ctx.verify_mode = ssl.CERT_NONE

HEADERS = {
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    "Accept": "text/plain",
}


def clean_response(text):
    """Extract actual content from API response, handling raw JSON and ads."""
    text = text.strip()
    # Strip deprecation notice
    if "IMPORTANT NOTICE" in text:
        idx = text.find("work normally.")
        if idx > 0:
            text = text[idx + len("work normally."):].strip()
    # Handle raw JSON responses
    if text.startswith("{"):
        try:
            data = json.loads(text)
            if "choices" in data:
                return clean_response(data["choices"][0]["message"]["content"])
            if "content" in data and data["content"]:
                return clean_response(data["content"])
            if "reasoning_content" in data:
                return clean_response(data.get("content") or data.get("reasoning_content", ""))
        except (json.JSONDecodeError, KeyError, IndexError):
            pass
    # Strip Pollinations ads/promos
    ad_patterns = [
        "pollinations.ai",
        "pollinations.AI",
        "powered by pollinations",
        "generated by pollinations",
        "support our mission",
        "🌸 ad",
        "🌸ad",
        "🌸",
    ]
    lines = text.split("\n")
    cleaned = []
    skip_next_blank = False
    for line in lines:
        stripped = line.strip().lower()
        # Skip ad lines
        is_ad = False
        if any(p.lower() in stripped for p in ad_patterns):
            if len(stripped) < 200:
                is_ad = True
        # Skip separator lines before/after ads
        if stripped == "---" or stripped == "***" or stripped == "___":
            is_ad = True
        if is_ad:
            skip_next_blank = True
            continue
        if skip_next_blank and not stripped:
            skip_next_blank = False
            continue
        skip_next_blank = False
        cleaned.append(line)
    # Also strip trailing ad lines
    while cleaned and not cleaned[-1].strip():
        cleaned.pop()
    text = "\n".join(cleaned).strip()
    return text


def call_ai(messages, retries=3):
    """Call Pollinations API with retries and fallback."""
    last_user = ""
    for m in messages:
        if m.get("role") == "user":
            last_user = m["content"]

    # Only send last 6 messages to keep requests small
    trimmed = messages[:1] + messages[-6:] if len(messages) > 7 else messages

    # Try POST first
    for attempt in range(retries):
        try:
            payload = json.dumps({"messages": trimmed}).encode("utf-8")
            req = urllib.request.Request(API_URL, data=payload, headers=HEADERS, method="POST")
            with urllib.request.urlopen(req, timeout=120, context=ssl_ctx) as resp:
                raw = resp.read().decode("utf-8")
                text = clean_response(raw)
                if text:
                    return text
        except Exception as e:
            print(f"  POST attempt {attempt+1} failed: {e}")
            time.sleep(1)

    # Fallback: GET with just the last message
    if last_user:
        try:
            url = API_URL + urllib.parse.quote(last_user)
            req = urllib.request.Request(url, headers={"User-Agent": HEADERS["User-Agent"]})
            with urllib.request.urlopen(req, timeout=120, context=ssl_ctx) as resp:
                raw = resp.read().decode("utf-8")
                text = clean_response(raw)
                if text:
                    return text
        except Exception as e:
            print(f"  GET fallback failed: {e}")

    return None


class ChatHandler(http.server.SimpleHTTPRequestHandler):
    def do_POST(self):
        if self.path == "/api/chat":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length)
            data = json.loads(body)
            messages = data.get("messages", [])

            reply = call_ai(messages)

            if reply:
                self.send_response(200)
                self.send_header("Content-Type", "text/plain; charset=utf-8")
                self.end_headers()
                self.wfile.write(reply.encode("utf-8"))
            else:
                self.send_response(502)
                self.send_header("Content-Type", "text/plain")
                self.end_headers()
                self.wfile.write(b"AI service unavailable. Try again.")
        else:
            self.send_response(404)
            self.end_headers()

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def log_message(self, fmt, *args):
        if "favicon" not in str(args[0]):
            print(f"  {args[0]}")


if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    server = http.server.HTTPServer(("", PORT), ChatHandler)
    print(f"\n  My AI Chatbot Server")
    print(f"  Open: http://localhost:{PORT}")
    print(f"  Press Ctrl+C to stop\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n  Server stopped.")
